import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { parseKnowledgeDirectory, publicKnowledgeRecords } from "./core.ts";

const root = process.cwd();
const records = publicKnowledgeRecords(parseKnowledgeDirectory(resolve(root, "knowledge")));
const outputPath = resolve(root, "src/data/knowledge-library.generated.ts");
const output = `// Generated by npm run knowledge:build. Do not edit directly.\nimport type { KnowledgeLibraryRecord } from "@/types/knowledge";\n\nexport const publicKnowledgeLibrary = ${JSON.stringify(records, null, 2)} as const satisfies readonly KnowledgeLibraryRecord[];\n`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, output, "utf8");
process.stdout.write(`Built ${records.length} public knowledge record(s).\n`);
